In [3]:
import pandas as pd
import great_expectations as gx
import json

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
# Caminho do arquivo CSV
arquivo = "/content/olist_order_items_dataset.csv"

# Leitura do CSV
df = pd.read_csv(arquivo)

# Padroniza nomes das colunas
df.columns = [c.upper() for c in df.columns]
df.head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,ORDER_ID,ORDER_ITEM_ID,PRODUCT_ID,SELLER_ID,SHIPPING_LIMIT_DATE,PRICE,FREIGHT_VALUE
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [11]:
# Criar o contexto do Great Expectations
context = gx.get_context()

# Criar uma fonte de dados baseada em pandas
data_source = context.data_sources.add_pandas(name="pandas_source")

# Criar um asset
data_asset = data_source.add_dataframe_asset(name="olist_asset")
batch_definition = data_asset.add_batch_definition_whole_dataframe("full_batch")

# Criar o batch com o dataframe
batch = batch_definition.get_batch(
    batch_parameters={"dataframe": df}
)

# Criar o validator
validator = context.get_validator(
    batch=batch,
    create_expectation_suite_with_name="suite_olist"
)

INFO:great_expectations.data_context.types.base:Created temporary directory '/tmp/tmpsky483xm' for ephemeral docs site
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [12]:
# Lista para guardar os resultados
resultados = []

# Regras de qualidade

# Não pode ser nulo
resultados.append(validator.expect_column_values_to_not_be_null("ORDER_ID"))
resultados.append(validator.expect_column_values_to_not_be_null("ORDER_ITEM_ID"))
resultados.append(validator.expect_column_values_to_not_be_null("PRODUCT_ID"))
resultados.append(validator.expect_column_values_to_not_be_null("SELLER_ID"))

# Valores válidos
resultados.append(validator.expect_column_values_to_be_between("PRICE", min_value=0.01))
resultados.append(validator.expect_column_values_to_be_between("FREIGHT_VALUE", min_value=0))

# Data não pode ser nula
resultados.append(validator.expect_column_values_to_not_be_null("SHIPPING_LIMIT_DATE"))

/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
# Cria uma chave única
df["ORDER_ITEM_KEY"] = df["ORDER_ID"].astype(str) + "_" + df["ORDER_ITEM_ID"].astype(str)

# Atualiza batch com nova coluna
batch = batch_definition.get_batch(
    batch_parameters={"dataframe": df}
)

validator = context.get_validator(
    batch=batch,
    expectation_suite_name="suite_olist"
)

# Verifica duplicidade
resultados.append(validator.expect_column_values_to_be_unique("ORDER_ITEM_KEY"))

/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1659: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
resumo = []

# Loop nos resultados para gerar um relatório simples
for r in resultados:
    resumo.append({
        "regra": r["expectation_config"]["type"],
        "coluna": r["expectation_config"]["kwargs"].get("column", ""),
        "sucesso": r["success"],
        "erros": r["result"].get("unexpected_count", 0)
    })

df_resumo = pd.DataFrame(resumo)
df_resumo

                                 regra               coluna  sucesso  erros
0  expect_column_values_to_not_be_null             ORDER_ID     True      0
1  expect_column_values_to_not_be_null        ORDER_ITEM_ID     True      0
2  expect_column_values_to_not_be_null           PRODUCT_ID     True      0
3  expect_column_values_to_not_be_null            SELLER_ID     True      0
4   expect_column_values_to_be_between                PRICE     True      0
5   expect_column_values_to_be_between        FREIGHT_VALUE     True      0
6  expect_column_values_to_not_be_null  SHIPPING_LIMIT_DATE     True      0
7    expect_column_values_to_be_unique       ORDER_ITEM_KEY     True      0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
import json

# Métricas manuais
relatorio = {
    "total_linhas": len(df),
    "nulos_order_id": int(df["ORDER_ID"].isnull().sum()),
    "nulos_product_id": int(df["PRODUCT_ID"].isnull().sum()),
    "nulos_seller_id": int(df["SELLER_ID"].isnull().sum()),
    "price_invalido": int((df["PRICE"] <= 0).sum()),
    "frete_invalido": int((df["FREIGHT_VALUE"] < 0).sum()),
    "duplicidade_item": int(df["ORDER_ITEM_KEY"].duplicated().sum())
}

# Mostra em formato JSON
print(json.dumps(relatorio, indent=2, ensure_ascii=False))

{
  "total_linhas": 112650,
  "nulos_order_id": 0,
  "nulos_product_id": 0,
  "nulos_seller_id": 0,
  "price_invalido": 0,
  "frete_invalido": 0,
  "duplicidade_item": 0
}

In [16]:
# Salva relatório das regras
df_resumo.to_csv("/content/relatorio_quality.csv", index=False)

# Salva métricas gerais
pd.DataFrame([relatorio]).to_csv("/content/metricas_quality.csv", index=False)

print("Arquivos salvos com sucesso!")

Arquivos salvos com sucesso!

In [ ]:
# Mapeamento do dataset para modelo de negócio
cdm = pd.DataFrame([
    {"original": "ORDER_ID", "cdm": "OrderId", "descricao": "Pedido"},
    {"original": "ORDER_ITEM_ID", "cdm": "LineNumber", "descricao": "Item"},
    {"original": "PRODUCT_ID", "cdm": "ProductId", "descricao": "Produto"},
    {"original": "SELLER_ID", "cdm": "VendorId", "descricao": "Vendedor"},
    {"original": "PRICE", "cdm": "UnitPrice", "descricao": "Preço"},
    {"original": "FREIGHT_VALUE", "cdm": "ShippingCost", "descricao": "Frete"},
    {"original": "SHIPPING_LIMIT_DATE", "cdm": "ShipDate", "descricao": "Envio"}
])

cdm

              original           cdm descricao
0             ORDER_ID       OrderId    Pedido
1        ORDER_ITEM_ID    LineNumber      Item
2           PRODUCT_ID     ProductId   Produto
3            SELLER_ID      VendorId  Vendedor
4                PRICE     UnitPrice     Preço
5        FREIGHT_VALUE  ShippingCost     Frete
6  SHIPPING_LIMIT_DATE      ShipDate     Envio

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [18]:
# Salva o mapeamento CDM
cdm.to_csv("/content/mapeamento_cdm.csv", index=False)